<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Core42\Command\AbstractCommand'              => __DIR__ . '/src/Core42/Command/AbstractCommand.php',
    'Core42\Db\Adapter\MasterServiceFactory'      => __DIR__ . '/src/Core42/Db/Adapter/MasterServiceFactory.php',
    'Core42\Db\Adapter\SlaveServiceFactory'       => __DIR__ . '/src/Core42/Db/Adapter/SlaveServiceFactory.php',
    'Core42\Db\ResultSet\ResultSet'               => __DIR__ . '/src/Core42/Db/ResultSet/ResultSet.php',
    'Core42\Db\RowGateway\RowGateway'             => __DIR__ . '/src/Core42/Db/RowGateway/RowGateway.php',
    'Core42\Db\TableGateway\AbstractTableGateway' => __DIR__ . '/src/Core42/Db/TableGateway/AbstractTableGateway.php',
    'Core42\Form\AbstractForm'                    => __DIR__ . '/src/Core42/Form/AbstractForm.php',
    'Core42\Hydrator\ModelHydrator'               => __DIR__ . '/src/Core42/Hydrator/ModelHydrator.php',
    'Core42\Model\Model'                          => __DIR__ . '/src/Core42/Model/Model.php',
    'Core42\Module'                               => __DIR__ . '/src/Core42/Module.php',
    'ChromePhp'                                   => __DIR__ . '/vendor/ChromePHP/ChromePhp.php',
    'FB'                                          => __DIR__ . '/vendor/FirePHP/lib/FirePHPCore/fb.php',
    'FirePHP'                                     => __DIR__ . '/vendor/FirePHP/lib/FirePHPCore/FirePHP.class.php',
    'FirePHPCore_FirePHPTest'                     => __DIR__ . '/vendor/FirePHP/tests/FirePHPCore/FirePHPTest.php',
    'FirePHPCore_FirePHPTest__TestObject'         => __DIR__ . '/vendor/FirePHP/tests/FirePHPCore/FirePHPTest.php',
    'FirePHP_Test_Class'                          => __DIR__ . '/vendor/FirePHP/tests/TestHelper.php',
);
