<?php
// Generated by Zend Framework 2
return array(
    'Core42\Command\AbstractCommand'                           => __DIR__ . '//src/Core42/Command/AbstractCommand.php',
    'Core42\Db\Adapter\MasterServiceFactory'                   => __DIR__ . '//src/Core42/Db/Adapter/MasterServiceFactory.php',
    'Core42\Db\Adapter\SlaveServiceFactory'                    => __DIR__ . '//src/Core42/Db/Adapter/SlaveServiceFactory.php',
    'Core42\Db\ResultSet\ResultSet'                            => __DIR__ . '//src/Core42/Db/ResultSet/ResultSet.php',
    'Core42\Db\RowGateway\RowGateway'                          => __DIR__ . '//src/Core42/Db/RowGateway/RowGateway.php',
    'Core42\Db\SqlQuery\SqlQuery'                              => __DIR__ . '//src/Core42/Db/SqlQuery/SqlQuery.php',
    'Core42\Db\TableGateway\AbstractTableGateway'              => __DIR__ . '//src/Core42/Db/TableGateway/AbstractTableGateway.php',
    'Core42\Db\TableGateway\Feature\MetadataFeature'           => __DIR__ . '//src/Core42/Db/TableGateway/Feature/MetadataFeature.php',
    'Core42\Form\AbstractForm'                                 => __DIR__ . '//src/Core42/Form/AbstractForm.php',
    'Core42\Hydrator\ModelHydrator'                            => __DIR__ . '//src/Core42/Hydrator/ModelHydrator.php',
    'Core42\Hydrator\Strategy\MysqlBooleanStrategy'            => __DIR__ . '//src/Core42/Hydrator/Strategy/MysqlBooleanStrategy.php',
    'Core42\Hydrator\Strategy\MysqlDatetimeStrategy'           => __DIR__ . '//src/Core42/Hydrator/Strategy/MysqlDatetimeStrategy.php',
    'Core42\Model\AbstractModel'                               => __DIR__ . '//src/Core42/Model/AbstractModel.php',
    'Core42\Model\DefaultModel'                                => __DIR__ . '//src/Core42/Model/DefaultModel.php',
    'Core42\Module'                                            => __DIR__ . '//src/Core42/Module.php',
    'Core42\ServiceManager\ServiceManagerStaticAwareInterface' => __DIR__ . '//src/Core42/ServiceManager/ServiceManagerStaticAwareInterface.php',
    'ClassTest'                                                => __DIR__ . '//tests/ClassTest.php',
);