<?php

/*
 * core42
 *
 * @package core42
 * @link https://github.com/kiwi-suite/core42
 * @copyright Copyright (c) 2010 - 2017 kiwi suite (https://www.kiwi-suite.com)
 * @license MIT License
 * @author kiwi suite <dev@kiwi-suite.com>
 */

namespace Core42;

use Core42\Form\Service\ElementFactory;
use Zend\Form\Element;
use Zend\Form\Fieldset;
use Zend\Form\Form;

return [
    'form_elements' => [
        'factories' => [
            Element\Button::class         => ElementFactory::class,
            Element\Captcha::class        => ElementFactory::class,
            Element\Checkbox::class       => ElementFactory::class,
            Element\Collection::class     => ElementFactory::class,
            Element\Color::class          => ElementFactory::class,
            Element\Csrf::class           => ElementFactory::class,
            Element\Date::class           => ElementFactory::class,
            Element\DateSelect::class     => ElementFactory::class,
            Element\DateTime::class       => ElementFactory::class,
            Element\DateTimeLocal::class  => ElementFactory::class,
            Element\DateTimeSelect::class => ElementFactory::class,
            Element::class                => ElementFactory::class,
            Element\Email::class          => ElementFactory::class,
            Fieldset::class               => ElementFactory::class,
            Element\File::class           => ElementFactory::class,
            Form::class                   => ElementFactory::class,
            Element\Hidden::class         => ElementFactory::class,
            Element\Image::class          => ElementFactory::class,
            Element\Month::class          => ElementFactory::class,
            Element\MonthSelect::class    => ElementFactory::class,
            Element\MultiCheckbox::class  => ElementFactory::class,
            Element\Number::class         => ElementFactory::class,
            Element\Password::class       => ElementFactory::class,
            Element\Radio::class          => ElementFactory::class,
            Element\Range::class          => ElementFactory::class,
            Element\Select::class         => ElementFactory::class,
            Element\Submit::class         => ElementFactory::class,
            Element\Text::class           => ElementFactory::class,
            Element\Textarea::class       => ElementFactory::class,
            Element\Time::class           => ElementFactory::class,
            Element\Url::class            => ElementFactory::class,
            Element\Week::class           => ElementFactory::class,
        ],
        'aliases' => [
            'button'         => Element\Button::class,
            'Button'         => Element\Button::class,
            'captcha'        => Element\Captcha::class,
            'Captcha'        => Element\Captcha::class,
            'checkbox'       => Element\Checkbox::class,
            'Checkbox'       => Element\Checkbox::class,
            'collection'     => Element\Collection::class,
            'Collection'     => Element\Collection::class,
            'color'          => Element\Color::class,
            'Color'          => Element\Color::class,
            'csrf'           => Element\Csrf::class,
            'Csrf'           => Element\Csrf::class,
            'date'           => Element\Date::class,
            'Date'           => Element\Date::class,
            'dateselect'     => Element\DateSelect::class,
            'dateSelect'     => Element\DateSelect::class,
            'DateSelect'     => Element\DateSelect::class,
            'datetime'       => Element\DateTime::class,
            'dateTime'       => Element\DateTime::class,
            'DateTime'       => Element\DateTime::class,
            'datetimelocal'  => Element\DateTimeLocal::class,
            'dateTimeLocal'  => Element\DateTimeLocal::class,
            'DateTimeLocal'  => Element\DateTimeLocal::class,
            'datetimeselect' => Element\DateTimeSelect::class,
            'dateTimeSelect' => Element\DateTimeSelect::class,
            'DateTimeSelect' => Element\DateTimeSelect::class,
            'element'        => Element::class,
            'Element'        => Element::class,
            'email'          => Element\Email::class,
            'Email'          => Element\Email::class,
            'fieldset'       => Fieldset::class,
            'Fieldset'       => Fieldset::class,
            'file'           => Element\File::class,
            'File'           => Element\File::class,
            'form'           => Form::class,
            'Form'           => Form::class,
            'hidden'         => Element\Hidden::class,
            'Hidden'         => Element\Hidden::class,
            'image'          => Element\Image::class,
            'Image'          => Element\Image::class,
            'month'          => Element\Month::class,
            'Month'          => Element\Month::class,
            'monthselect'    => Element\MonthSelect::class,
            'monthSelect'    => Element\MonthSelect::class,
            'MonthSelect'    => Element\MonthSelect::class,
            'multicheckbox'  => Element\MultiCheckbox::class,
            'multiCheckbox'  => Element\MultiCheckbox::class,
            'MultiCheckbox'  => Element\MultiCheckbox::class,
            'multiCheckBox'  => Element\MultiCheckbox::class,
            'MultiCheckBox'  => Element\MultiCheckbox::class,
            'number'         => Element\Number::class,
            'Number'         => Element\Number::class,
            'password'       => Element\Password::class,
            'Password'       => Element\Password::class,
            'radio'          => Element\Radio::class,
            'Radio'          => Element\Radio::class,
            'range'          => Element\Range::class,
            'Range'          => Element\Range::class,
            'select'         => Element\Select::class,
            'Select'         => Element\Select::class,
            'submit'         => Element\Submit::class,
            'Submit'         => Element\Submit::class,
            'text'           => Element\Text::class,
            'Text'           => Element\Text::class,
            'textarea'       => Element\Textarea::class,
            'Textarea'       => Element\Textarea::class,
            'time'           => Element\Time::class,
            'Time'           => Element\Time::class,
            'url'            => Element\Url::class,
            'Url'            => Element\Url::class,
            'week'           => Element\Week::class,
            'Week'           => Element\Week::class,
        ],
    ],
];
